### ISSUE TITLE
program does not launch

### ISSUE THREAD

**Issue by jdrake9734** [rbrasga/SPPD_BOT#1]
Hi, I've been waiting for someone to do something like this for almost a year, and I can't believe I actually found this only 15 hours after your last release! 

I understand coding enough to be dangerous and have everything set up according to your instructions, however, it will not launch the app within Bluestacks. I've tried a few settings starting with your recommended display but it seems that I cannot put Bluestacks into full-screen mode until the app is actually launched - and the program seems to be reaching pretty far into the corner when it runs (it hits my Recycle Bin if I do not have Bluestacks maximized and there is no way that I can get the app icon that far into the corner). 

I have downloaded heaps of gits over the years and never even thought about posting an issue, but for a fellow SPPD-er, I am glad to do what I'm able! 

(Other note, in your instructions for how to start the program, you say "python SSPD.py" - when I copied/pasted I couldn't figure out for the life of me what was wrong this time! Eventually, I found and changed it to python SPPD.py and it started.)

(Second note, how hard do you think it would be to make a program that counts energy spent and tells you exactly what your opponent's energy levels are? I have no idea how I'd go about this, but reading through your code I almost feel like it could be possible, and enormously awesome as well!)

Thanks so much for doing this!

**Comment by rbrasga** [comment]
Message me on discord @LuckyPenguin#3617. We will walk through it.

The initial click in the top left corner is to bring the pc out of the screensaver.

You don’t need the app to be full-screen, just bluestacks to be maximized. Because SPPD crashes frequently and requires closing out of the app with the ‘x’ on the sppd tab.

**Comment by rbrasga** [comment]
Probably worth mentioning, you can have SPPD (the app) running in it’s tab in bluestacks, then launch SPPD.py.

It should work from the home screen or butter’s house with the PVP Battle Button screen.

Lastly, I’m coming out with a GUI, and there’s a lot of quality of life improvements I have yet to make. Please contact me on discord and we should be able to get it up and running in no time.

I got in the top 10 on the weekend leaderboard using this.

**Comment by rbrasga** [comment]
Ø  (Second note, how hard do you think it would be to make a program that counts energy spent and tells you exactly what your opponent's energy levels are? I have no idea how I'd go about this, but reading through your code I almost feel like it could be possible, and enormously awesome as well!)

o   5-years and team of Ph.D. students.

o   Realistically though, it’s just a bit of machine learning that I have roadmap’d to be done about a year from now.

o   Beyond just a bot, I would love to implement a statistics gathering tool that records matches, lockers, and packs, etc.

o   If you have any feature requests, please file them as bugs (there’s no such thing as a dumb feature request)

**Comment by rbrasga** [comment]
Sorry, final email. Please file a bug including a screenshot. I believe I found the problem. Your icon probably doesn’t match mine. I’ll fix it in the next release.

**Comment by jdrake9734** [comment]
How do I find you on discord?

**Comment by rbrasga** [comment]
Create a discord account at discordapp.com, then in the top right button, click Add Friend: LuckyPenguin#3617

I have a major batch of fixes coming soon that will make it way easier to run (won’t require python, pytesser, etc).

**Comment by rbrasga** [comment]
Closed, invalid.
