### ISSUE TITLE
Is program still functional / is the discord still open

### ISSUE THREAD

**Issue by Drymander** [rbrasga/SPPD_BOT#2]
Hi rbrasga,

Thank yo for your effort in putting this together.  I'm interested in contributing to the project, however, I have not been able to find the discord (which I know from the readme is required for getting an access code).  Would be happy to join, let me know if it's easy to find or if it's more of a private invitation thing.

Many thanks.

**Comment by rbrasga** [comment]
Sorry buddy. This is a private research project to make sure SPPD is being honest based on statistical analysis. I am not accepting contributors and the discord is dead.

Bots are not allowed in the game, and if it makes you feel better, there's ZERO (0) publicly available bots.

I'll update the README.

**Comment by Drymander** [comment]
Appreciate your honesty! Thanks for the response.
